<?php

namespace App\WebRadio\Playlists;

class MetalPlaylist implements PlaylistInterface {
    public function get() : array
    {
        return [
            'Alestorm - Nancy The Tavern Wench' => 'https://www.youtube.com/watch?v=_MV23cy3FGs',
            'Alestorm - Scraping The Barrel' => 'https://www.youtube.com/watch?v=TQ2Kg7P0o7I',
            'Alestorm - Shipwrecked' => 'https://www.youtube.com/watch?v=fjGM2IKkFpE',
            'Alestorm - You Are a Pirate' => 'https://www.youtube.com/watch?v=CvXdmQh7BHY',
            'Angra - Gentle Change' => 'https://www.youtube.com/watch?v=5wvkq_unzgE',
            'Angra - Lisbon' => 'https://www.youtube.com/watch?v=-IM8VhksIPE',
            'Angra - Make Believe' => 'https://www.youtube.com/watch?v=fSv9nslftPI',
            'Angra - Nova Era' => 'https://www.youtube.com/watch?v=t8J0YonTDbI',
            'Angra - Rebirth' => 'https://www.youtube.com/watch?v=Tj0DAKEmMo4',
            'Astralion - Mysterious and Victorious' => 'https://www.youtube.com/watch?v=1BdbQkHCXMo',
            'Avantasia - Farewell' => 'https://www.youtube.com/watch?v=aHnthk0ar7I',
            'Avantasia - The Scarecrow' => 'https://www.youtube.com/watch?v=fuEZVhnFsPk',
            'Axxis - Wind In The Night - Shalom' => 'https://www.youtube.com/watch?v=uJFm9DRsLMA',
            'Blind Guardian - A Past and Future Secret' => 'https://www.youtube.com/watch?v=aTHPHtQhZP4',
            'Blind Guardian - Curse My Name' => 'https://www.youtube.com/watch?v=dogKjhy-q7A',
            'Blind Guardian - Mirror Mirror' => 'https://www.youtube.com/watch?v=zSEvhskdCtY',
            'Blind Guardian - Skalds and Shadows' => 'https://www.youtube.com/watch?v=_3_S1Q40HZo',
            'Blind Guardian - The Bards Song - In The Forest' => 'https://www.youtube.com/watch?v=ypjbba2tAIE',
            'Braia - Bloom - Ode à Joyce' => 'https://www.youtube.com/watch?v=EA9UKfIGzZc',
            'Braia - Brunebriante Papoula Dançante' => 'https://www.youtube.com/watch?v=Am3YFg4Z--w',
            'Braia - Lua' => 'https://www.youtube.com/watch?v=3qEXtAoCmBQ',
            'Braia - Sláinte a La Brasilis' => 'https://www.youtube.com/watch?v=lHdjYSm9mek',
            'Braia - Tempos Idos' => 'https://www.youtube.com/watch?v=RlujcclpoBQ',
            'Café Irlanda - Se Eu Cair Não Me Levante' => 'https://www.youtube.com/watch?v=NEHMUl95e2w',
            'Confraria da Costa - Rússia Reversa' => 'https://www.youtube.com/watch?v=DjHsE5DZ8FQ',
            'Dark Moor - A Lament Of Misery' => 'https://www.youtube.com/watch?v=RJxjdmfr0b0',
            'Dark Moor - Alaric de Marnac' => 'https://www.youtube.com/watch?v=CWPTht7e-NI',
            'Dark Moor - Canción Del Pirata' => 'https://www.youtube.com/watch?v=11GLmOQvcjI',
            'Dark Moor - From Dawn To Dusk' => 'https://www.youtube.com/watch?v=kideLz4sI_Y',
            'Dark Moor - Memories' => 'https://www.youtube.com/watch?v=me1P-9-DtUs',
            'Dark Moor - Mio Cid' => 'https://www.youtube.com/watch?v=hVjec2vGfDU',
            'Dark Moor - The Dark Moor' => 'https://www.youtube.com/watch?v=zn50zeV_lrQ',
            'Detonator e as Musas do Metal - Metaleiro' => 'https://www.youtube.com/watch?v=Uufks9mgZDU',
            'DragonForce - Cry Thunder' => 'https://www.youtube.com/watch?v=rNLr62qMI1c',
            'DragonForce - Dawn Over a New World' => 'https://www.youtube.com/watch?v=JAAf_5CGEnY',
            'DragonForce - Heroes Of Your Time' => 'https://www.youtube.com/watch?v=4B28e4zPx3o',
            'DragonForce - Seasons' => 'https://www.youtube.com/watch?v=RVeYtJNN5zw',
            'DragonForce - Valley Of The Damned' => 'https://www.youtube.com/watch?v=HlFO1YVOTXs',
            'DragonForce - Where Dragons Rule' => 'https://www.youtube.com/watch?v=SD-CDrLm3ew',
            'Dynasty - Goldenland' => 'https://www.youtube.com/watch?v=3QmOPnqqt-k',
            'Ensiferum - In My Sword I Trust' => 'https://www.youtube.com/watch?v=UiUvcfSjHQs',
            'Ensiferum - Lai Lai Hei' => 'https://www.youtube.com/watch?v=DZ-rRTR1MZY',
            'Ensiferum - Victory Song' => 'https://www.youtube.com/watch?v=zhXs7TESKD8',
            'Epica - Cry For The Moon' => 'https://www.youtube.com/watch?v=Ra3C1c6QKPk',
            'Epica - Quietus' => 'https://www.youtube.com/watch?v=2vw884S3V3Y',
            'Epica - Triumph of Defeat' => 'https://www.youtube.com/watch?v=qhGkCJdEG2M',
            'Falconer - Carnival of Disgust' => 'https://www.youtube.com/watch?v=KlD6AXCmc-g',
            'Faun - Tanz Mit Mir - Duett Mit Santiano' => 'https://www.youtube.com/watch?v=CK5MdsewTjM',
            'Faun - Tinta' => 'https://www.youtube.com/watch?v=VRCvpMgwuak',
            'Faun - Walpurgisnacht' => 'https://www.youtube.com/watch?v=vIdn_Gx1NAM',
            'Finntroll - Trollhammeren' => 'https://www.youtube.com/watch?v=HGhZ35Dk6xc',
            'Flogging Molly - Drunken Lullabies' => 'https://www.youtube.com/watch?v=ogzlmuH7nuY',
            'Galneryus - The Nightcraver' => 'https://www.youtube.com/watch?v=gGlkxRdhT2o',
            'Galneryus - Whisper In The Red Sky' => 'https://www.youtube.com/watch?v=pcQNsxFdHOw',
            'Gloryhammer - Angus McFife' => 'https://www.youtube.com/watch?v=agRN6UkXg8o',
            'Gloryhammer - Hail to Crail' => 'https://www.youtube.com/watch?v=aYSBZvukqfA',
            'HB - Hanki Elämä' => 'https://www.youtube.com/watch?v=GjorQqBub9k',
            'Helloween - I Can' => 'https://www.youtube.com/watch?v=VeCxK9PxQ20',
            'Helloween - If I Could Fly' => 'https://www.youtube.com/watch?v=WNM_QJZVrl8',
            'Helloween - Power' => 'https://www.youtube.com/watch?v=mOAfRCzzps8',
            'Helloween - World of Fantasy' => 'https://www.youtube.com/watch?v=CDwSqg6Bv4c',
            'Holy Knights - Lord Of Nightmares' => 'https://www.youtube.com/watch?v=XvKGNIsvT7M',
            'Holy Knights - Sir Percival - Immortal Knights' => 'https://www.youtube.com/watch?v=YQT8NdggUzE',
            'Korpiklaani - Juodaan Viinaa' => 'https://www.youtube.com/watch?v=zIdN8f06Lbs',
            'Korpiklaani - Metsamies' => 'https://www.youtube.com/watch?v=MdgLR9RttZQ',
            'Korpiklaani - Vodka' => 'https://www.youtube.com/watch?v=e7kJRGPgvRQ',
            'Mago de Oz - Fiesta Pagana' => 'https://www.youtube.com/watch?v=Dm79PqVs4oM',
            'Mago de Oz - Molino de Viento' => 'https://www.youtube.com/watch?v=ZwLf2wSrkEc',
            'Massacration - Lets Ride To Metal Land' => 'https://www.youtube.com/watch?v=1eoq8ZFlgqQ',
            'Matanza - Estamos Todos Bêbados' => 'https://www.youtube.com/watch?v=wCqttkKQVoI',
            'Metal Nobre - Apocalipse' => 'https://www.youtube.com/watch?v=YlPKj2BwnYU',
            'Nightwish - Alpenglow' => 'https://www.youtube.com/watch?v=GnHMp8WIg1Q',
            'Nightwish - Bare Grace Misery' => 'https://www.youtube.com/watch?v=xCHtDgirizs',
            'Nightwish - Elvenpath' => 'https://www.youtube.com/watch?v=Rk-e6lI2pks',
            'Nightwish - Ever Dream' => 'https://www.youtube.com/watch?v=jdFCSF54Jd4',
            'Nightwish - Last Ride Of The Day' => 'https://www.youtube.com/watch?v=6FRK4QPmCVk',
            'Nightwish - Moondance' => 'https://www.youtube.com/watch?v=umn3iBag7KM',
            'Nightwish - She Is My Sin' => 'https://www.youtube.com/watch?v=gbCJ6kVXXmE',
            'Nightwish - The Islander' => 'https://www.youtube.com/watch?v=hltIYAfWi7U',
            'Northern Kings - We Dont Need Another Hero ' => 'https://www.youtube.com/watch?v=MTfkCOeKuMk',
            'Rhapsody of Fire - A New Saga Begins' => 'https://www.youtube.com/watch?v=p53WDzXZZdA',
            'Rhapsody of Fire - A Tale Of Magic' => 'https://www.youtube.com/watch?v=J1CL8eCh9O4',
            'Rhapsody of Fire - Dargor Shadowlord Of The Black Mountain - EP' => 'https://www.youtube.com/watch?v=qrcvdvIQZJE',
            'Rhapsody of Fire - Emerald Sword - EP' => 'https://www.youtube.com/watch?v=4Ixg-1X6DtI',
            'Rhapsody of Fire - I Belong to the Stars' => 'https://www.youtube.com/watch?v=6ke2gvgqeCw',
            'Rhapsody of Fire - The Last Winged Unicorn' => 'https://www.youtube.com/watch?v=tGoH-tIzW5Q',
            'Rhapsody of Fire - The March of Swordmaster' => 'https://www.youtube.com/watch?v=m3stG1f95dQ',
            'Rhapsody of Fire - The Village of Dwarves' => 'https://www.youtube.com/watch?v=J6qmQaleuv0',
            'Rhapsody of Fire - Triumph For My Magic Steel' => 'https://www.youtube.com/watch?v=pFH7kdkyDaQ',
            'Rhapsody of Fire - Wisdom of the Kings' => 'https://www.youtube.com/watch?v=3qGIDc45KoU',
            'Sabaton - Smoking Snakes' => 'https://www.youtube.com/watch?v=OhNB1HTECnY',
            'Santiano - Santiano' => 'https://www.youtube.com/watch?v=JNOWW706vkQ',
            'Seventh Avenue - Infinite King' => 'https://www.youtube.com/watch?v=AI38PWuvHM4',
            'Seventh Avenue - Storm II' => 'https://www.youtube.com/watch?v=E--wj6B-JXk',
            'Shaman - Distant Thunder' => 'https://www.youtube.com/watch?v=CJg-9zdY8lg',
            'Shaman - Fairy Tale' => 'https://www.youtube.com/watch?v=f9KmYyir-MM',
            'Shaman - For Tomorrow' => 'https://www.youtube.com/watch?v=zGAXP4eUcxU',
            'Shaman - In The Dark' => 'https://www.youtube.com/watch?v=Ij12Vxj5M_A',
            'Skiltron - Bagpipes of War' => 'https://www.youtube.com/watch?v=4aZGwLXxHvc',
            'Sonata Arctica - Fullmoon' => 'https://www.youtube.com/watch?v=G4xWSGjbeW4',
            'Sonata Arctica - Paid In Full' => 'https://www.youtube.com/watch?v=2J2xu9BVq3Q',
            'Sonata Arctica - Victorias Secret ' => 'https://www.youtube.com/watch?v=O126HRqReto',
            'SpellBlast - Glory To The Gem' => 'https://www.youtube.com/watch?v=IZGyd2OPtnY',
            'SpellBlast - Goblins Song' => 'https://www.youtube.com/watch?v=E4sP-wv-WNo',
            'SpellBlast - Lost In The Forest' => 'https://www.youtube.com/watch?v=95n3uVysE84',
            'Spellblast - Ragnarok - Dream Of The End' => 'https://www.youtube.com/watch?v=vpIaIcpWbFg',
            'SpellBlast - Sign of the Unicorns' => 'https://www.youtube.com/watch?v=QUU_wIuIuss',
            'SpellBlast - Soldiers Angels' => 'https://www.youtube.com/watch?v=7FBPCvTRRkE',
            'Stratovarius - Darkest Hours' => 'https://www.youtube.com/watch?v=TjCebDeGDtI',
            'Stratovarius - Hunting High and Low' => 'https://www.youtube.com/watch?v=I4mSbZT-eog',
            'Symphony X - Accolade II' => 'https://www.youtube.com/watch?v=91Ui6bRlHlU',
            'Terra Celta - Até o último gole' => 'https://www.youtube.com/watch?v=bZMXj00UQ5I',
            'Terra Celta - Ressaca' => 'https://www.youtube.com/watch?v=kOHzcqKyl3Q',
            'Tuatha De Danann - Abracadabra' => 'https://www.youtube.com/watch?v=qyPWPbdULXs',
            'Tuatha De Danann - Behold The Horned King' => 'https://www.youtube.com/watch?v=XO0hU0gQRvc',
            'Tuatha De Danann - Believe Its True' => 'https://www.youtube.com/watch?v=oH5ISEHb9nI',
            'Tuatha De Danann - Brazuzan - Taller Than a Hill' => 'https://www.youtube.com/watch?v=GZeHDJo4byk',
            'Tuatha De Danann - Land of Youth - Tir Nan Og' => 'https://www.youtube.com/watch?v=KRt_F14RWlI',
            'Tuatha de Danann - Lover Of The Queen' => 'https://www.youtube.com/watch?v=cbgHAkEL2a4',
            'Tuatha De Danann - The Last Words' => 'https://www.youtube.com/watch?v=PvSxbOLt2a0',
            'Tuatha De Danann - Trova Di Danú' => 'https://www.youtube.com/watch?v=6fPdG0sqT4E',
            'Tuatha de Danann - We re Back' => 'https://www.youtube.com/watch?v=BAVeDsrjPgs',
            'Turisas - Stand Up and Fight' => 'https://www.youtube.com/watch?v=BagVYW00XPs',
            'Turisas - The March of the Varangian Guard' => 'https://www.youtube.com/watch?v=U0Vr5FFxxtU',
            'Twilight Force - Flight of the Sapphire Dragon' => 'https://www.youtube.com/watch?v=8-OzvIL4d2w',
            'Twilight Force - The Power Of The Ancient Force' => 'https://www.youtube.com/watch?v=0qRc8tod7K4',
            'Van Canto - Last Night of the Kings' => 'https://www.youtube.com/watch?v=vqGiiGiVz1o',
            'Wind Rose - To Erebor' => 'https://www.youtube.com/watch?v=-qF1EQXIG1c',
            'Wizard - Hammer Bow Axe and Sword' => 'https://www.youtube.com/watch?v=17Sy70edqTY',
            'Xandria - Kill The Sun' => 'https://www.youtube.com/watch?v=Rl41AtVPtb4',
        ];
    }
}
